KEYWORDS = {
    "اطبع": "print",
    "اذا": "if",
    "والا": "else",
    "بينما": "while",
    "لكل": "for",
    "في": "in",
    "صح": "True",
    "خطأ": "False",
    "دالة": "def",
    "اطبع": "print",
    "ارجع": "return",
    "ادخل": "INPUT",
    "نوع": "TYPE",
    "رقم": "NUMBER_CAST",
}
