[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "arabicpy"
version = "0.1.0"
description = "Arabic programming language"
authors = [
    {name = "Saud"}
]


[project.scripts]
arabicpy = "arabicpy.__main__:run"


[tool.setuptools]
packages = ["arabicpy"]