"""Al-Baa Design System -- design tokens.

Self-contained on purpose: this whole `design_system/` folder is copied
verbatim into every new PySide6 project generated by Al-Baa Code (see
`arabicpy/pyside_template.py`), so it must not import anything from the
rest of the `arabicpy` package -- only the standard library and PySide6.

The color values below mirror `arabicpy/theme.py`'s `PALETTES` (the IDE's
own design tokens). If Al-Baa's brand colors change, update both places.
"""

from dataclasses import dataclass

DARK = "dark"
LIGHT = "light"
MODES = (DARK, LIGHT)


@dataclass(frozen=True)
class Palette:
    mode: str
    canvas: str
    surface: str
    surface_alt: str
    border: str
    text: str
    text_muted: str
    text_dim: str
    text_on_accent: str
    accent: str
    accent_hover: str
    accent_pressed: str
    accent2: str
    success: str
    success_hover: str
    danger: str
    danger_hover: str
    shadow: str
    selection: str


PALETTES = {
    DARK: Palette(
        mode=DARK,
        canvas="#15171c",
        surface="#1b1e24",
        surface_alt="#20242c",
        border="#2c313c",
        text="#e7e9ef",
        text_muted="#a7adba",
        text_dim="#6b7280",
        text_on_accent="#ffffff",
        accent="#6C8CFF",
        accent_hover="#7f9bff",
        accent_pressed="#5877e0",
        accent2="#3DDBC0",
        success="#3ecf8e",
        success_hover="#4fe0a0",
        danger="#ef5350",
        danger_hover="#f4726f",
        shadow="#000000",
        selection="#33507a",
    ),
    LIGHT: Palette(
        mode=LIGHT,
        canvas="#eef1f6",
        surface="#ffffff",
        surface_alt="#f3f6f9",
        border="#dbe0e8",
        text="#191c22",
        text_muted="#5b6472",
        text_dim="#8891a1",
        text_on_accent="#ffffff",
        accent="#4C6FEF",
        accent_hover="#3d5ce0",
        accent_pressed="#3049b8",
        accent2="#14A98A",
        success="#1f9d63",
        success_hover="#249e6c",
        danger="#d1453b",
        danger_hover="#e0554b",
        shadow="#94a3b8",
        selection="#bcdcf7",
    ),
}

RADIUS = {"sm": 6, "md": 10, "lg": 14, "xl": 20}

SPACING = {"xxs": 2, "xs": 4, "sm": 8, "md": 12, "lg": 16, "xl": 24, "xxl": 32, "xxxl": 48}


@dataclass(frozen=True)
class TypeStyle:
    family: str
    size: int
    weight: int


_FONT_STACK = '"Segoe UI", "Tahoma", Arial, sans-serif'

TYPOGRAPHY = {
    "display": TypeStyle(_FONT_STACK, 28, 700),
    "title": TypeStyle(_FONT_STACK, 20, 700),
    "subtitle": TypeStyle(_FONT_STACK, 15, 600),
    "body": TypeStyle(_FONT_STACK, 13, 400),
    "caption": TypeStyle(_FONT_STACK, 11, 400),
    "monospace": TypeStyle('"Consolas", "Courier New", monospace', 12, 400),
}
