KEYWORDS = {
    "اطبع": "print",
    "اذا": "if",
    "والا": "else",
    "بينما": "while",
    "لكل": "for",
    "في": "in",
    "صح": "True",
    "خطأ": "False",
    "دالة": "def",
    "اطبع": "print",
    "ارجع": "return",
    "و": "and",
    "او": "or",
    "أو": "or",
    "ليس": "not",
    "توقف": "break",
    "استمر": "continue",
    "تجاوز": "pass",
    "ادخل": "INPUT",
    "نوع": "TYPE",
    "رقم": "NUMBER_CAST",
}

